motion_segments:
  - segment_id: 1
    joint_names:
      [
        base_to_mast_joint,
        carriage_to_tool_joint,
        mast_to_carriage_joint,
        tool_mount_joint,
      ]
    target_positions: [0.50, 0.50, 0.50, 0.0]
    max_velocity: 0.3
    max_acceleration: 0.5
    position_tolerance: 0.001

  - segment_id: 2
    joint_names:
      [
        base_to_mast_joint,
        carriage_to_tool_joint,
        mast_to_carriage_joint,
        tool_mount_joint,
      ]
    target_positions: [0, 0, 0, 0.0]
    max_velocity: 0.3
    max_acceleration: 0.5
    position_tolerance: 0.001
